import { useEffect, useState } from 'react';
import attendanceService from '../../services/attendanceService';
import projectService from '../../services/projectService';

export default function SEAttendance(){
  const [rows,setRows]=useState([]),[projects,setProjects]=useState([]),[token,setToken]=useState(''),[projectId,setProjectId]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  const load=async()=>{try{setError('');const [a,p]=await Promise.all([attendanceService.list(),projectService.list()]);setRows(a);setProjects(p||[]);if(!projectId&&p?.[0]?.id)setProjectId(p[0].id)}catch(e){setError(e.response?.data?.message||'Unable to load attendance.')}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const scan=async()=>{try{setError('');if(!token.trim())throw new Error('Enter or scan a worker QR token.');if(!projectId)throw new Error('Select a project.');await attendanceService.checkInByQr({qrCodeToken:token.trim(),projectId:Number(projectId)});setToken('');await load()}catch(e){setError(e.response?.data?.message||e.message||'QR check-in failed.')}};
  const verify=async(id,verified)=>{try{await attendanceService.verify(id,verified);await load()}catch(e){setError(e.response?.data?.message||'Verification failed.')}};
  const checkout=async(id)=>{try{await attendanceService.checkOut(id);await load()}catch(e){setError(e.response?.data?.message||'Check-out failed.')}};
  return <div className="page-content"><div className="page-header"><div><h1>Site Attendance</h1><p>Scan a worker QR token, monitor active shifts and verify attendance.</p></div></div>{error&&<div className="panel" style={{padding:12,color:'#dc2626',marginBottom:16}}>{error}</div>}<div className="panel" style={{padding:20,marginBottom:20}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr auto',gap:12,alignItems:'end'}}><label>Project<select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Worker QR token<input value={token} onChange={e=>setToken(e.target.value)} placeholder="WRK-..."/></label><button className="primary-button" onClick={scan}>Check In by QR</button></div></div><div className="panel"><table className="data-table"><thead><tr><th>Worker</th><th>Project</th><th>Check In</th><th>Check Out</th><th>Hours</th><th>Status</th><th>Verification</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan="8">Loading…</td></tr>:rows.length?rows.map(r=><tr key={r.id}><td>{r.workerName||'—'}</td><td>{r.projectName||'—'}</td><td>{r.checkIn?new Date(r.checkIn).toLocaleString():'—'}</td><td>{r.checkOut?new Date(r.checkOut).toLocaleString():'Active'}</td><td>{r.hoursWorked??'—'}</td><td>{r.status||'—'}</td><td>{r.verificationStatus||'PENDING'}</td><td>{!r.checkOut&&<button className="secondary-button" onClick={()=>checkout(r.id)}>Check Out</button>} {r.verificationStatus==='PENDING'&&<button className="primary-button" onClick={()=>verify(r.id,true)}>Verify</button>}</td></tr>):<tr><td colSpan="8">No attendance records.</td></tr>}</tbody></table></div></div>;
}
