
export const PERMISSIONS = {
  // Common
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',
  PROFILE_EDIT: 'PROFILE_EDIT',
  NOTIFICATION_VIEW: 'NOTIFICATION_VIEW',

  // Company
  COMPANY_VIEW: 'COMPANY_VIEW',
  COMPANY_ADMIN_MANAGE: 'COMPANY_ADMIN_MANAGE',
  USER_VIEW: 'USER_VIEW',
  USER_MANAGE: 'USER_MANAGE',

  // Projects
  PROJECT_VIEW: 'PROJECT_VIEW',
  PROJECT_MANAGE: 'PROJECT_MANAGE',

  // Tasks
  TASK_VIEW: 'TASK_VIEW',
  TASK_MANAGE: 'TASK_MANAGE',

  // Workforce
  WORKFORCE_VIEW: 'WORKFORCE_VIEW',
  WORKFORCE_MANAGE: 'WORKFORCE_MANAGE',

  // Attendance
  ATTENDANCE_VIEW: 'ATTENDANCE_VIEW',
  ATTENDANCE_MARK: 'ATTENDANCE_MARK',
  SHIFT_MANAGE: 'SHIFT_MANAGE',

  // Equipment
  EQUIPMENT_VIEW: 'EQUIPMENT_VIEW',
  EQUIPMENT_MANAGE: 'EQUIPMENT_MANAGE',

  // Materials
  MATERIAL_VIEW: 'MATERIAL_VIEW',
  MATERIAL_MANAGE: 'MATERIAL_MANAGE',

  // Finance
  FINANCE_VIEW: 'FINANCE_VIEW',
  FINANCE_MANAGE: 'FINANCE_MANAGE',

  // AI
  AI_VIEW: 'AI_VIEW',

  // Reports
  REPORT_VIEW: 'REPORT_VIEW',

  // Documents
  DOCUMENT_VIEW: 'DOCUMENT_VIEW',
  DOCUMENT_MANAGE: 'DOCUMENT_MANAGE',

  // Daily logs
  DAILY_LOG_VIEW: 'DAILY_LOG_VIEW',
  DAILY_LOG_MANAGE: 'DAILY_LOG_MANAGE',

  // Site issues
  SITE_ISSUE_VIEW: 'SITE_ISSUE_VIEW',
  SITE_ISSUE_MANAGE: 'SITE_ISSUE_MANAGE',

  // System
  SYSTEM_ADMIN_MANAGE: 'SYSTEM_ADMIN_MANAGE',
};


/**
 * Role → Permission mapping.
 */
export const ROLE_PERMISSIONS = {

  SUPER_ADMIN: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.COMPANY_ADMIN_MANAGE,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_MANAGE,

    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_MANAGE,

    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_MANAGE,

    PERMISSIONS.WORKFORCE_VIEW,
    PERMISSIONS.WORKFORCE_MANAGE,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.SHIFT_MANAGE,

    PERMISSIONS.EQUIPMENT_VIEW,
    PERMISSIONS.EQUIPMENT_MANAGE,

    PERMISSIONS.MATERIAL_VIEW,
    PERMISSIONS.MATERIAL_MANAGE,

    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_MANAGE,

    PERMISSIONS.AI_VIEW,
    PERMISSIONS.REPORT_VIEW,

    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_MANAGE,

    PERMISSIONS.DAILY_LOG_VIEW,
    PERMISSIONS.DAILY_LOG_MANAGE,

    PERMISSIONS.SITE_ISSUE_VIEW,
    PERMISSIONS.SITE_ISSUE_MANAGE,

    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.SYSTEM_ADMIN_MANAGE,
    PERMISSIONS.PROFILE_EDIT,
  ],


  COMPANY_ADMIN: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.COMPANY_ADMIN_MANAGE,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_MANAGE,

    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_MANAGE,

    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_MANAGE,

    PERMISSIONS.WORKFORCE_VIEW,
    PERMISSIONS.WORKFORCE_MANAGE,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.SHIFT_MANAGE,

    PERMISSIONS.EQUIPMENT_VIEW,
    PERMISSIONS.EQUIPMENT_MANAGE,

    PERMISSIONS.MATERIAL_VIEW,
    PERMISSIONS.MATERIAL_MANAGE,

    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_MANAGE,

    PERMISSIONS.AI_VIEW,
    PERMISSIONS.REPORT_VIEW,

    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_MANAGE,

    PERMISSIONS.DAILY_LOG_VIEW,
    PERMISSIONS.DAILY_LOG_MANAGE,

    PERMISSIONS.SITE_ISSUE_VIEW,
    PERMISSIONS.SITE_ISSUE_MANAGE,

    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.PROFILE_EDIT,
  ],


  PROJECT_MANAGER: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_MANAGE,

    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_MANAGE,

    PERMISSIONS.WORKFORCE_VIEW,
    PERMISSIONS.WORKFORCE_MANAGE,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.SHIFT_MANAGE,

    PERMISSIONS.EQUIPMENT_VIEW,
    PERMISSIONS.EQUIPMENT_MANAGE,

    PERMISSIONS.MATERIAL_VIEW,
    PERMISSIONS.MATERIAL_MANAGE,

    PERMISSIONS.AI_VIEW,
    PERMISSIONS.REPORT_VIEW,

    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_MANAGE,

    PERMISSIONS.DAILY_LOG_VIEW,
    PERMISSIONS.DAILY_LOG_MANAGE,

    PERMISSIONS.SITE_ISSUE_VIEW,

    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.PROFILE_EDIT,
  ],


  SITE_ENGINEER: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.PROJECT_VIEW,

    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_MANAGE,

    PERMISSIONS.WORKFORCE_VIEW,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,

    PERMISSIONS.EQUIPMENT_VIEW,

    PERMISSIONS.MATERIAL_VIEW,
    PERMISSIONS.MATERIAL_MANAGE,

    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_MANAGE,

    PERMISSIONS.DAILY_LOG_VIEW,
    PERMISSIONS.DAILY_LOG_MANAGE,

    PERMISSIONS.SITE_ISSUE_VIEW,
    PERMISSIONS.SITE_ISSUE_MANAGE,

    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.PROFILE_EDIT,
  ],


  CONTRACTOR: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.PROJECT_VIEW,

    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_MANAGE,

    PERMISSIONS.WORKFORCE_VIEW,
    PERMISSIONS.WORKFORCE_MANAGE,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,

    PERMISSIONS.EQUIPMENT_VIEW,

    PERMISSIONS.MATERIAL_VIEW,
    PERMISSIONS.MATERIAL_MANAGE,

    PERMISSIONS.FINANCE_VIEW,

    PERMISSIONS.DOCUMENT_VIEW,

    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.PROFILE_EDIT,
  ],


  WORKER: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.PROJECT_VIEW,

    PERMISSIONS.TASK_VIEW,

    PERMISSIONS.WORKFORCE_VIEW,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,

    PERMISSIONS.EQUIPMENT_VIEW,

    PERMISSIONS.MATERIAL_VIEW,

    PERMISSIONS.DOCUMENT_VIEW,

    PERMISSIONS.NOTIFICATION_VIEW,
    PERMISSIONS.PROFILE_EDIT,
  ],
};


export function getRolePermissions(role) {
  const normalized = String(role || '')
    .toUpperCase()
    .replace(/\s+/g, '_');

  return ROLE_PERMISSIONS[normalized] || [];
}


export function hasPermission(userPermissions, requiredPermission) {
  if (!requiredPermission) {
    return false;
  }

  if (!Array.isArray(userPermissions)) {
    return false;
  }

  return userPermissions.includes(requiredPermission);
}