import { useEffect, useState } from 'react';
import { FileText, Plus, CheckCircle2, XCircle } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { useData } from '../context/DataContext';
import { dailyLogService } from '../services/dailyLogService';

export default function Step7DailyLogs() {
  const { user } = useAuth(); const { projects=[] } = useData();
  const [logs,setLogs]=useState([]); const [projectId,setProjectId]=useState(''); const [form,setForm]=useState({logDate:new Date().toISOString().slice(0,10),workSummary:'',blockers:'',safetyNotes:'',weather:'',progressPercentage:''}); const [notice,setNotice]=useState('');
  const load=async()=>{try{setLogs(await dailyLogService.list(projectId||undefined));}catch(e){console.error(e)}}; useEffect(()=>{load()},[projectId]);
  const submit=async e=>{e.preventDefault(); if(!projectId)return; try{const x=await dailyLogService.create({...form,projectId,progressPercentage:form.progressPercentage===''?null:Number(form.progressPercentage)});setLogs(p=>[x,...p]);setForm({...form,workSummary:'',blockers:'',safetyNotes:''});setNotice('Daily log submitted successfully.');}catch(err){setNotice(err?.response?.data?.message||'Unable to submit log.')}};
  const review=async(id,ok)=>{try{const x=ok?await dailyLogService.approve(id):await dailyLogService.reject(id);setLogs(p=>p.map(l=>l.id===id?x:l));}catch(err){alert(err?.response?.data?.message||'Review failed')}};
  const canReview=['SUPER_ADMIN','COMPANY_ADMIN','PROJECT_MANAGER'].includes(user?.role);
  return <div className="dashboard-page"><section className="hero-row"><div><p className="eyebrow"><FileText size={14}/> Daily Logs</p><h1>Site Daily Logs</h1></div></section>{notice&&<div className="panel" style={{marginTop:16,padding:12}}>{notice}</div>}
    <div style={{display:'grid',gridTemplateColumns:'minmax(300px,420px) 1fr',gap:18,marginTop:18}}>
      <div className="panel" style={{padding:20}}><h3><Plus size={16}/> Submit Daily Log</h3><form onSubmit={submit} style={{display:'grid',gap:11,marginTop:14}}><select required value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input type="date" required value={form.logDate} onChange={e=>setForm({...form,logDate:e.target.value})}/><textarea required rows="4" placeholder="Work completed today" value={form.workSummary} onChange={e=>setForm({...form,workSummary:e.target.value})}/><input type="number" min="0" max="100" placeholder="Progress %" value={form.progressPercentage} onChange={e=>setForm({...form,progressPercentage:e.target.value})}/><input placeholder="Weather" value={form.weather} onChange={e=>setForm({...form,weather:e.target.value})}/><textarea rows="2" placeholder="Blockers / delays" value={form.blockers} onChange={e=>setForm({...form,blockers:e.target.value})}/><textarea rows="2" placeholder="Safety notes" value={form.safetyNotes} onChange={e=>setForm({...form,safetyNotes:e.target.value})}/><button className="primary-button" disabled={!projectId}>Submit Log</button></form></div>
      <div className="panel" style={{padding:20}}><h3>Submitted Logs</h3><div style={{display:'grid',gap:10,marginTop:14}}>{logs.map(l=><div key={l.id} style={{padding:14,border:'1px solid var(--border)',borderRadius:10}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><strong>{l.projectName}</strong><span>{l.status}</span></div><div style={{fontSize:12,color:'var(--muted)',margin:'5px 0'}}>{l.logDate} · {l.createdBy}</div><p style={{fontSize:13}}>{l.workSummary}</p>{l.progressPercentage!=null&&<div style={{fontSize:12}}>Progress: <strong>{l.progressPercentage}%</strong></div>}{canReview&&l.status==='SUBMITTED'&&<div style={{display:'flex',gap:7,marginTop:10}}><button className="secondary-button" onClick={()=>review(l.id,true)}><CheckCircle2 size={13}/> Approve</button><button className="secondary-button" onClick={()=>review(l.id,false)}><XCircle size={13}/> Reject</button></div>}</div>)}{logs.length===0&&<p style={{color:'var(--muted)'}}>No daily logs yet.</p>}</div></div>
    </div></div>;
}
