import { useEffect, useState } from 'react';
import { BarChart3, Download, RefreshCw } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { useData } from '../context/DataContext';
import { reportService } from '../services/reportService';

export default function Step7Reports(){
 const {user}=useAuth(); const {projects=[]}=useData(); const [reports,setReports]=useState([]); const [projectId,setProjectId]=useState(''); const [type,setType]=useState('PROJECT_PERFORMANCE'); const [title,setTitle]=useState('Project Performance Report'); const [busy,setBusy]=useState(false);
 const load=async()=>{try{setReports(await reportService.list(projectId||undefined))}catch(e){console.error(e)}}; useEffect(()=>{load()},[projectId]);
 const generate=async()=>{setBusy(true);try{const r=await reportService.generate({title,reportType:type,projectId:projectId||null});setReports(p=>[r,...p])}catch(e){alert(e?.response?.data?.message||'Report generation failed')}finally{setBusy(false)}};
 const exportJson=r=>{const blob=new Blob([r.summaryJson||'{}'],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${(r.title||'report').replace(/[^a-z0-9]+/gi,'_')}.json`;a.click();URL.revokeObjectURL(url)};
 return <div className="dashboard-page"><section className="hero-row"><div><p className="eyebrow"><BarChart3 size={14}/> Reports</p><h1>Operational Reports</h1></div></section><div className="panel" style={{marginTop:18,padding:16,display:'flex',gap:10,flexWrap:'wrap'}}><select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Company / portfolio</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)}><option>PROJECT_PERFORMANCE</option><option>WORKFORCE_ANALYTICS</option><option>RESOURCE_UTILIZATION</option><option>FINANCIAL_SUMMARY</option><option>PROJECT_COMPLETION</option></select><input value={title} onChange={e=>setTitle(e.target.value)} style={{minWidth:240}}/><button className="primary-button" disabled={busy} onClick={generate}><RefreshCw size={14}/> {busy?'Generating…':'Generate Report'}</button></div><div style={{display:'grid',gap:12,marginTop:16}}>{reports.map(r=><div className="panel" key={r.id} style={{padding:18}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><strong>{r.title}</strong><div style={{fontSize:12,color:'var(--muted)',marginTop:4}}>{r.reportType} · {r.projectName||'Company'} · {r.generatedBy}</div></div><button className="secondary-button" onClick={()=>exportJson(r)}><Download size={13}/> Export JSON</button></div><pre style={{marginTop:12,padding:12,background:'var(--panel-soft)',borderRadius:8,overflow:'auto',fontSize:11}}>{JSON.stringify(JSON.parse(r.summaryJson||'{}'),null,2)}</pre></div>)}{reports.length===0&&<div className="panel" style={{padding:40,textAlign:'center',color:'var(--muted)'}}>No generated reports yet.</div>}</div></div>
}
